### ISSUE TITLE
HeaderComponent

### ISSUE THREAD

**Issue by KhoaWorkHub** [KhoaWorkHub/Group-3-OJT#1]
create the header component

**Comment by KhoaWorkHub** [comment]
@NguyenTuan03 @Lolakien @Bluerry74 check giúp tớ xem dc chưa nhé !!!!

**Comment by NguyenTuan03** [comment]
ok được rồi nha !

Vào Th 6, 16 thg 8, 2024 vào lúc 09:55 Trần Đăng Khoa <
***@***.***> đã viết:

**Comment by KhoaWorkHub** [comment]
done !!!
